# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib D:/Zynq_project/mouse_basys3_FPGA/mouse_basys3_FPGA.srcs/sources_1/new/mouse_basys3_FPGA.v
read_xdc D:/Zynq_project/mouse_basys3_FPGA/mouse_basys3_FPGA.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files D:/Zynq_project/mouse_basys3_FPGA/mouse_basys3_FPGA.srcs/constrs_1/new/pin.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Zynq_project/mouse_basys3_FPGA/mouse_basys3_FPGA.cache/wt [current_project]
set_property parent.project_dir D:/Zynq_project/mouse_basys3_FPGA [current_project]
catch { write_hwdef -file mouse_basys3_FPGA.hwdef }
synth_design -top mouse_basys3_FPGA -part xc7a35tcpg236-1
write_checkpoint mouse_basys3_FPGA.dcp
report_utilization -file mouse_basys3_FPGA_utilization_synth.rpt -pb mouse_basys3_FPGA_utilization_synth.pb
